---
include:
  - board: eyelash_sofle_right
  - board: eyelash_sofle_leftt
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: eyelash_sofle_studio_leftt
  - board: eyelash_sofle_leftt
    shield: settings_reset
